DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS QUIZZES;
DROP TABLE IF EXISTS RESULTS;

CREATE TABLE STUDENTS
(ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL);

CREATE TABLE QUIZZES
(ID INTEGER PRIMARY KEY NOT NULL,
SUBJECT VARCHAR,
NUM_QUESTIONS INTEGER,
DATE VARCHAR);

CREATE TABLE RESULTS
(STUDENT_ID INT NOT NULL,
QUIZ_ID INT NOT NULL,
SCORE INT NOT NULL);